export const PROGRESS = {
    REWORK__SCANNING: "REWORK__SCANNING",
    REWORK__FAIL_SCANNING: "REWORK__FAIL_SCANNING",
    REWORK__SUCCESS_SCANNING: "REWORK__SUCCESS_SCANNING",

    REWORK__SENDING_V4_INFO_TO_CLOUD: "REWORK__SENDING_V4_INFO_TO_CLOUD",
    REWOWK__FAIL_SENDING_V4_INFO_TO_CLOUD: "REWOWK__FAIL_SENDING_V4_INFO_TO_CLOUD",
    REWOWK__SUCCESS_SENDING_V4_INFO_TO_CLOUD: "REWOWK__SUCCESS_SENDING_V4_INFO_TO_CLOUD",

    REWORK__DONWLOADING_PLUME_CAS_FROM_CLOUD: "REWORK__DONWLOADING_PLUME_CAS_FROM_CLOUD",
    REWORK__FAIL_DONWLOADING_PLUME_CAS_FROM_CLOUD: "REWORK__FAIL_DONWLOADING_PLUME_CAS_FROM_CLOUD",
    REWORK__SUCCESS_DONWLOADING_PLUME_CAS_FROM_CLOUD: "REWORK__SUCCESS_DONWLOADING_PLUME_CAS_FROM_CLOUD",

    REWORK__OPENNING_SSH_SERVER_ON_V4: "REWORK__OPENNING_SSH_SERVER_ON_V4",
    REWORK__FAIL_OPENNING_SSH_SERVER_ON_V4: "REWORK__FAIL_OPENNING_SSH_SERVER_ON_V4",
    REWORK__SUCCESS_OPENNING_SSH_SERVER_ON_V4: "REWORK__SUCCESS_OPENNING_SSH_SERVER_ON_V4",

    REWORK__SENDING_FW_TO_V4: "REWORK__SENDING_FW_TO_V4",
    REWORK__FAIL_SENDING_FW_TO_V4: "REWORK__FAIL_SENDING_FW_TO_V4",
    REWORK__SUCCESS_SENDING_FW_TO_V4: "REWORK__SUCCESS_SENDING_FW_TO_V4",

    REWORK__SENDING_PLUME_CAS_TO_V4: "REWORK__SENDING_PLUME_CAS_TO_V4",
    REWORK__FAIL_SENDING_PLUME_CAS_TO_V4: "REWORK__FAIL_SENDING_PLUME_CAS_TO_V4",
    REWORK__SUCCESS_SENDING_PLUME_CAS_TO_V4: "REWORK__SUCCESS_SENDING_PLUME_CAS_TO_V4",

    REWORK__INSTALLING_PLUME_CAS_ON_V4: "REWORK__INSTALLING_PLUME_CAS_ON_V4",
    REWORK__FAIL_INSTALLING_PLUME_CAS_ON_V4: "REWORK__FAIL_INSTALLING_PLUME_CAS_ON_V4",
    REWORK__SUCCESS_INSTALLING_PLUME_CAS_ON_V4: "REWORK__SUCCESS_INSTALLING_PLUME_CAS_ON_V4",

    REWORK__INSTALLING_FW_FOR_V4: "REWORK__INSTALLING_FW_FOR_V4",
    REWORK__FAIL_INSTALLING_FW_FOR_V4: "REWORK__FAIL_INSTALLING_FW_FOR_V4",
    REWORK__SUCCESS_INSTALLING_FW_FOR_V4: "REWORK__SUCCESS_INSTALLING_FW_FOR_V4",

    REWORK__SENDING_UPGRADED_LOG_TO_CLOUD: "REWORK__SENDING_UPGRADED_LOG_TO_CLOUD",
    REWORK__FAIL_SENDING_UPGRADED_LOG_TO_CLOUD: "REWORK__FAIL_SENDING_UPGRADED_LOG_TO_CLOUD",
    REWORK__SUCCESS_SENDING_UPGRADED_LOG_TO_CLOUD: "REWORK__SUCCESS_SENDING_UPGRADED_LOG_TO_CLOUD",
};

export const MODE = {
    REWORK__ALL_AUTO: "REWORK__ALL_AUTO",
    REWORK__ALL_MANUAL: "REWORK__ALL_MANUAL"
}

export const ACTION = {
    REWORK__UPGRADE_REWORK_SOURCE: "REWORK__UPGRADE_REWORK_SOURCE"
}